function [optTheta, cost] = batchLearn(visibleSize, hiddenSize, ...
									   lambda, sparsityParam, ...
									   beta, patches, ...
									   theta)

options = struct;
options.Method = 'lbfgs'; 
options.maxIter = 600;
options.display = 'on';
option.useMex = 0;

%batch learning
[optTheta, cost] = minFunc( @(p) SpLinAeCostGrad(p, ...
                                   visibleSize, hiddenSize, ...
                                   lambda, sparsityParam, ...
                                   beta, patches), ...
                              theta, options);

endfunction